---
title: "Projects"
---

In the summer of 2020 I took a GIS course based in R. This was my first experience coding and learning about data science and it made me realize how important these skills can be in biology. Here is a collection of links! 

### [Building a project website](https://ewapman.github.io/)

##### In this project I:
- Learned the basics of RStudio
- Was introduced to Rmarkdown, YMAL, CSS, and HTML
- Created code to construct and personalize a website 
- Familiarized myself with Github and learned why is important for version control and publishing

### [Analysis of COVID-19 Data](https://ewapman.github.io/geog-176A-labs/lab-02.html)

##### In this project I:
- Learned how to use dplyr verbs to manipulate nationwide data for the COVID-19 pandemic
- Learned how to join two data sets
- Created tables and plots 
- Learned how to use lags and the rolling mean to calculate new cases and the 7 day average 

### [Distances and Projections](https://ewapman.github.io/geog-176A-labs/lab-03.html)

##### In this project I:
- Calculated the distances of US cities to various US borders
- Built simple feature objects from R packages and CSVs to use as spatial data 
- Manipulated map projections and geometries
- Created maps using ggplot 


